import DesignProvider from '@/common/providers/design_provider'
import type { Metadata } from 'next'
import '@/styles/globals.scss'
import { AuthProvider } from '@/lib/firebase/context/auth'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
} : {
    children: React.ReactNode
}){
    return (
        <html lang='ja'>
            <body>
                <AuthProvider>
                    <DesignProvider>{children}</DesignProvider>
                </AuthProvider>
            </body>
        </html>
    )
}